# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# 名称
name: Java CI with Maven
# 触发条件
on:
  push:
    branches: [ "main" ] # main分支 push 时触发
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: scp_upload_file #上传文件到服务器
      uses: garygrossgarten/github-action-scp@release
      with:
        local: '/home/runner/work/fgrapp/fgrapp/target/fgrapp.jar' #打包文件的路径
        remote: '/app/fgrapp/fgrapp.jar' #放到服务器的目录
        host: ${{ secrets.HOST }} #服务器ip地址
        username: ${{ secrets.USERNAME }} #服务器ssh用户名
        password: ${{ secrets.PASSWORD }} #服务器ssh密码
        port: ${{ secrets.PORT }} # 服务器ssh端口（默认22）
    - name: deploy_app #开始部署
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} #服务器ip地址
        username: ${{ secrets.USERNAME }} #服务器ssh用户名
        password: ${{ secrets.PASSWORD }} #服务器ssh密码
        port: ${{ secrets.PORT }} # 服务器ssh端口（默认22）
        script: |
          cd /app/fgrapp
          ./restart.sh
